### PR TITLE
Updated to react@15.2.1. Removed unknown props from the input.

### PR DESCRIPTION
**Pull request by vzhidal**
Should fix issue#16. There is one test failure, but that was the same without my commit. I've removed onSelectStart event: react said that this is an unknown property for inputs and I haven't found any browser where this type of event was fired on an input.

### CODE REVIEW

**Comment by freeranger** [comment]
@vzhidal This fails the CI build so is unlikely to get merged - perhaps you could fix it up and hopefully @vlad-ignatov will merge it in soon?

**Comment by vzhidal** [comment]
@freeranger As I mentioned in my comment there was an issue in tests without my commit. For now I'm not sure that I understand how to fix that. The issue is in props.test.jsx. 'If the "value" is not set the corresponding attribute should not be set.' Do you have any ideas how to fix that?

**Comment by freeranger** [comment]
@vzhidal Ok sorry, I didn't see that.
Sorry, I don't know how to fix that - I'm pretty new to react development :/
I guess we need input from @vlad-ignatov to take a look and decide if he wants to merge this.
The react guys sure think it's important to get rid of these warnings...

**Comment by vlad-ignatov** [comment]
Thank you for that PR. In fact I fixed that myself along with many other issues and this one is no longer relevant.

**Pull request closed without merging**
