### PR TITLE
Calling preventDefault in onTouchEnd handler

### PR DESCRIPTION
**Pull request by lanceon**
Fix addresses this issue:
https://github.com/vlad-ignatov/react-numeric-input/issues/44

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
This is perfect, thank you. Can I only suggest that you add `this.onTouchEnd = this.onTouchEnd.bind(this)` to the constructor (just like it is done for `this.stop`? This way you will not have to bind on each `render`.

**Comment by lanceon** [comment]
This would be correct, thanks.
Updated: https://github.com/vlad-ignatov/react-numeric-input/pull/56/files

**Comment by vlad-ignatov** [comment]
Thank you for your contribution. This will be included in the next release soon.

**Comment by lanceon** [comment]
Yw. Thanks.

**Comment by mamadoo** [comment]
I still have this problem, can you explain what to do?

**Pull request merged**
