### PR TITLE
Ability to decrement input value with a different step size

### PR DESCRIPTION
**Pull request by sbhaleka**
I've added a separate 'downStep' property to allow setting a different step size when decrementing the value. The need for this arose as the project I'm working on requires the "price" input component to have different step sizes given the range of values (See below)
```
From | To         | Step Size 
0    | 0.9999     |  0.0001
1    | 9.99       |  0.01
10   | 99.9       |  0.1
100  | infinity   |  1.0
```
So for e.g. if component is showing value 10 pressing the UP key should take the value to 10.1 (step size 0.1) but pressing DOWN key should go to 9.99 (step size 0.01).

### CODE REVIEW

**Comment by vlad-ignatov** [comment]
Thank you  for this. Looks like a good addition to the component and the code changes are well written.

That being said, I think I have different architectural ideas of achieving the same thing but before I share them, could you explain how are you using this? I guess you have a piece of logic externally somewhere that given the current value will provide the next `step` and `downStep` prop values?

**Comment by sbhaleka** [comment]
That's exactly right. There's a code in the back-end that picks `step` and `downStep` given a price point and sends it to the front-end. Every time user changes the price in the input component we send that value to the BE to do the step picking. 

BE has some business logic to evaluate which price range is applicable for the given context and price point and it picks `step` and `downStep` property based on that logic. So when the price is exactly within the range both values will be equal. Only in case when the price is moving from one range to the other, there will be a difference in their values.

**Comment by vlad-ignatov** [comment]
OK then. Thanks for sharing. I think having  a backend involved in such a discrete front-end "event" makes your case unique.

I had plans to make some props like `min`, `max`, `step` and `precision` more dynamic than they are now because in rare cases, having to re-render to pass new props is simply not good enough. In fact I already did that for `precision` at https://github.com/vlad-ignatov/react-numeric-input/commit/4c7280825a496a3fa0ca7591be494d09962aebe5.  The idea is to simply allow for these props to also be functions and call them if they are.

This could also solve your case if you didn't have to involve the backend (which also makes that interaction asynchronous). Having a step function could look like
```js
<NumericInput  step={(component, direction) => {
    if (component.state.value == 10) {
        return direction == "up" ? 0.1 : 0.01;
    }
    // other custom conditions...

    // default
    return 1;
}}/>
```

In my opinion those prop functions must not be async. Otherwise that would significantly increase to complexity of the entire component. For people like you, who are sending requests to a back-end service to determine the value, re-rendering with different props will continue to be the better solution.

A think I will merge your PR soon just to cover those rare cases and then add the "function" option on top of it. Frankly, if I were you I would consider fetching a set of rules from the backend once and then building a step function that uses those rules (assuming that it is possible) so that people can use the component in real time.

**Comment by sbhaleka** [comment]
I agree, Making these props dynamic is a better solution. I think you can decline my PR in that case. 

The rules of range picking are still bit too complicated to bring into the FE. I think I still would want to keep them in the BE.  So after your change I'll still get the two step values from BE once the value in the component is changed. I'll then use the `step` function to pick the right step value based on the `direction`.

Any ideas when you'll be able to release that change.

Thanks,

**Comment by vlad-ignatov** [comment]
Well, I only get to work on this for a few hour per week now but the code is ready. I just need to do some more testing, update the readme and fix a few other things so I guess it will take about a week.

**Comment by sbhaleka** [comment]
got it. I'll wait for the release then. You can decline this PR.

**Comment by vlad-ignatov** [comment]
2.2.0 is now on NPM. I hope you can confirm if that works for you.

**Comment by sbhaleka** [comment]
I've tested it. It works like a charm :). Thanks.

**Comment by vlad-ignatov** [comment]
Thank you!

**Pull request closed without merging**
